In [1]:
import numpy as np
import pandas as pd

works = pd.DataFrame({
    '작가': ['김유정', '김유정', '김유정',
             '현진건', '현진건',
             '이상', '이상',
             '나도향', '나도향',
             '채만식', '이효석'],
    '작품': ['봄봄', '동백꽃', '만무방',
             '운수 좋은 날', 'B사감과 러브레터',
             '날개', '권태',
             '벙어리 삼룡이', '물레방아',
             '레디메이드 인생', '메밀꽃 필 무렵'],
    '연도': [1935, 1936, 1934,
             1924, 1925,
             1936, 1937,
             1925, 1925,
             1934, np.nan],
    '글자수': [12500, 9800, 13600,
              11200, 7400,
              18300, 14100,
              16800, 14500,
              22000, 11800],
})

authors = pd.DataFrame({
    '작가': ['김유정', '현진건', '이상', '나도향', '채만식', '이효석', '염상섭'],
    '생년': [1908, 1900, 1910, 1902, 1902, 1907, 1897],
    '몰년': [1937, 1943, 1937, 1926, 1950, 1942, 1963],
})

print("works:")
display(works)
print("\nauthors:")
display(authors)

works:

     작가         작품      연도    글자수
0   김유정         봄봄  1935.0  12500
1   김유정        동백꽃  1936.0   9800
2   김유정        만무방  1934.0  13600
3   현진건    운수 좋은 날  1924.0  11200
4   현진건  B사감과 러브레터  1925.0   7400
5    이상         날개  1936.0  18300
6    이상         권태  1937.0  14100
7   나도향    벙어리 삼룡이  1925.0  16800
8   나도향       물레방아  1925.0  14500
9   채만식   레디메이드 인생  1934.0  22000
10  이효석   메밀꽃 필 무렵     NaN  11800

authors:

    작가    생년    몰년
0  김유정  1908  1937
1  현진건  1900  1943
2   이상  1910  1937
3  나도향  1902  1926
4  채만식  1902  1950
5  이효석  1907  1942
6  염상섭  1897  1963

## Q1

### Q1(a)

In [2]:
# (i) shape
print("shape:", works.shape)

# (ii) dtypes
print("\ndtypes:")
print(works.dtypes)

# (iii) describe
print("\ndescribe:")
works.describe()

shape: (11, 4)

dtypes:
작가      object
작품      object
연도     float64
글자수      int64
dtype: object

describe:

                연도           글자수
count    10.000000     11.000000
mean   1931.100000  13818.181818
std       5.546771   4080.641661
min    1924.000000   7400.000000
25%    1925.000000  11500.000000
50%    1934.000000  13600.000000
75%    1935.750000  15650.000000
max    1937.000000  22000.000000

연도 열은 `float64`, 글자수 열은 `int64`인데, 연도 열에 `NaN`이 포함되어 있기 때문이다.

### Q1(b)

In [3]:
print(works.isna().sum())

작가     0
작품     0
연도     1
글자수    0
dtype: int64

연도 열에만 1건의 결측치가 존재한다. 이는 이효석의 '메밀꽃 필 무렵' 발표 연도가 누락된 것이다.

### Q1(c)

In [4]:
works2 = works.copy()
works2['연도'] = works2['연도'].fillna(1936).astype(int)

print("works2.dtypes:")
print(works2.dtypes)
print("\nworks2.tail(3):")
works2.tail(3)

works2.dtypes:
작가     object
작품     object
연도      int64
글자수     int64
dtype: object

works2.tail(3):

     작가        작품    연도    글자수
8   나도향      물레방아  1925  14500
9   채만식  레디메이드 인생  1934  22000
10  이효석  메밀꽃 필 무렵  1936  11800

`fillna(1936)`으로 결측값을 1936으로 채우고 `astype(int)`로 `float64`에서 `int64`로 형변환했다.

## Q2

### Q2(a)

In [5]:
# 1. 1930년 이후 발표된 작품
after_1930 = works2[works2['연도'] >= 1930]
print("1930년 이후 작품:")
display(after_1930)

# 2. 김유정 또는 이상의 작품
kim_or_lee = works2[works2['작가'].isin(['김유정', '이상'])]
print("\n김유정 또는 이상의 작품:")
display(kim_or_lee)

1930년 이후 작품:

     작가        작품    연도    글자수
0   김유정        봄봄  1935  12500
1   김유정       동백꽃  1936   9800
2   김유정       만무방  1934  13600
5    이상        날개  1936  18300
6    이상        권태  1937  14100
9   채만식  레디메이드 인생  1934  22000
10  이효석  메밀꽃 필 무렵  1936  11800

김유정 또는 이상의 작품:

    작가   작품    연도    글자수
0  김유정   봄봄  1935  12500
1  김유정  동백꽃  1936   9800
2  김유정  만무방  1934  13600
5   이상   날개  1936  18300
6   이상   권태  1937  14100

불 인덱싱으로 조건에 맞는 행만 추출했다. `after_1930`은 연도가 1930 이상인 7개 작품을 담고 있다.

### Q2(b)

In [6]:
def categorize(n: int) -> str:
    if n < 10000:
        return '짧음'
    elif n <= 15000:
        return '보통'
    else:
        return '긴'

works2['분량'] = works2['글자수'].apply(categorize)
works2[['작품', '글자수', '분량']]

           작품    글자수  분량
0          봄봄  12500  보통
1         동백꽃   9800  짧음
2         만무방  13600  보통
3     운수 좋은 날  11200  보통
4   B사감과 러브레터   7400  짧음
5          날개  18300   긴
6          권태  14100  보통
7     벙어리 삼룡이  16800   긴
8        물레방아  14500  보통
9    레디메이드 인생  22000   긴
10   메밀꽃 필 무렵  11800  보통

`categorize` 함수는 글자수를 받아 세 단계의 분량 카테고리를 반환한다. `apply()`로 새 열을 벡터화 방식으로 만들 수 있다.

### Q2(c)

In [7]:
works2.sort_values(by=['연도', '글자수'], ascending=[True, False])

     작가         작품    연도    글자수  분량
3   현진건    운수 좋은 날  1924  11200  보통
7   나도향    벙어리 삼룡이  1925  16800   긴
8   나도향       물레방아  1925  14500  보통
4   현진건  B사감과 러브레터  1925   7400  짧음
9   채만식   레디메이드 인생  1934  22000   긴
2   김유정        만무방  1934  13600  보통
0   김유정         봄봄  1935  12500  보통
5    이상         날개  1936  18300   긴
10  이효석   메밀꽃 필 무렵  1936  11800  보통
1   김유정        동백꽃  1936   9800  짧음
6    이상         권태  1937  14100  보통

`sort_values`의 `by`와 `ascending`에 리스트를 전달하여 다중 기준 정렬을 한 번에 수행한다.

---
## Q3

### Q3(a)

In [8]:
works2.groupby('작가')['글자수'].agg(['mean', 'count', 'sum']).rename(
    columns={'mean': '평균 글자수', 'count': '작품 수', 'sum': '총 글자수'}
)

           평균 글자수  작품 수  총 글자수
작가
김유정  11966.666667     3  35900
나도향  15650.000000     2  31300
이상   16200.000000     2  32400
이효석  11800.000000     1  11800
채만식  22000.000000     1  22000
현진건   9300.000000     2  18600

채만식이 총 글자수 22000자로 단일 작품 기준 가장 긴 글을 썼고, 김유정이 3편으로 작품 수가 가장 많다.

### Q3(b)

In [9]:
works2['분량'].value_counts()

분량
보통    6
긴     3
짧음    2
Name: count, dtype: int64

'보통' 분량의 작품이 가장 많고, '짧음'과 '긴' 작품이 뒤를 잇는다. 이는 수록된 작품들이 중편 단편 위주임을 보여준다.

### Q3(c)

In [10]:
works2.groupby(['작가', '분량']).size()

작가   분량
김유정  보통    2
     짧음    1
나도향  긴     1
     보통    1
이상   긴     1
     보통    1
이효석  보통    1
채만식  긴     1
현진건  보통    1
     짧음    1
dtype: int64

가장 많은 작품 수를 가진 조합은 (김유정, 보통)으로 2편인데, 이는 김유정이 주로 1만~1만5천 자 사이의 중편 단편을 선호했음을 시사한다.

## Q4

### Q4(a)

In [11]:
full = pd.merge(works2, authors, on='작가', how='left')
print("shape:", full.shape)
display(full)

shape: (11, 7)

     작가         작품    연도    글자수  분량    생년    몰년
0   김유정         봄봄  1935  12500  보통  1908  1937
1   김유정        동백꽃  1936   9800  짧음  1908  1937
2   김유정        만무방  1934  13600  보통  1908  1937
3   현진건    운수 좋은 날  1924  11200  보통  1900  1943
4   현진건  B사감과 러브레터  1925   7400  짧음  1900  1943
5    이상         날개  1936  18300   긴  1910  1937
6    이상         권태  1937  14100  보통  1910  1937
7   나도향    벙어리 삼룡이  1925  16800   긴  1902  1926
8   나도향       물레방아  1925  14500  보통  1902  1926
9   채만식   레디메이드 인생  1934  22000   긴  1902  1950
10  이효석   메밀꽃 필 무렵  1936  11800  보통  1907  1942

authors에만 있는 '염상섭'은 full에 포함되지 않는다. how='left'는 왼쪽 표(works2)의 행만 기준으로 삼아 오른쪽 표(authors)에서 일치하는 행을 붙이기 때문에, 왼쪽에 없는 작가는 결과에 나타나지 않는다.

### Q4(b)

In [12]:
full['집필 당시 나이'] = full['연도'] - full['생년']
full[['작가', '작품', '연도', '생년', '집필 당시 나이']]

     작가         작품    연도    생년  집필 당시 나이
0   김유정         봄봄  1935  1908        27
1   김유정        동백꽃  1936  1908        28
2   김유정        만무방  1934  1908        26
3   현진건    운수 좋은 날  1924  1900        24
4   현진건  B사감과 러브레터  1925  1900        25
5    이상         날개  1936  1910        26
6    이상         권태  1937  1910        27
7   나도향    벙어리 삼룡이  1925  1902        23
8   나도향       물레방아  1925  1902        23
9   채만식   레디메이드 인생  1934  1902        32
10  이효석   메밀꽃 필 무렵  1936  1907        29

`연도 - 생년`의 벡터화 연산으로 각 작품의 집필 당시 나이를 한 번에 계산했다.

### Q4(c)

In [13]:
result = (
    full.groupby('작가')['집필 당시 나이']
    .mean()
    .sort_values()
)
print(result)

작가
나도향    23.0
현진건    24.5
이상     26.5
김유정    27.0
이효석    29.0
채만식    32.0
Name: 집필 당시 나이, dtype: float64

가장 어린 나이에 작품을 발표한 작가는 이상으로 평균 약 26세에 작품을 썼으며, 가장 늦은 나이에 작품을 발표한 작가는 채만식으로 평균 약 32세이다.